version: "3.0"
services:
  app:
    build: ./app
    volumes:
      - ./app/src:/var/www/app
      - vendor:/var/www/app/vendor
    ports:
      - "8000:8000"
  db:
    image: mysql:8.0.33
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  web:
    image: nginx:1.25
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/log:/var/log/nginx
      - ./app/src:/var/www/app
      - vendor:/var/www/app/vendor
    ports:
      - "80:80"
    working_dir: /var/www/app

volumes:
  vendor:
